kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: susi-tweetbot
  namespace: tweetbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: susi-tweetbot
    spec:
      containers:
      - name: susi-tweetbot
        image: aliayubkhan/susi_tweetbot:latest
        env:
        - name: TWITTER_CK
          value: "H42NjkkKfe0gLE27Or3rGS59T"
        - name: TWITTER_CS
          value: "2OoXDEdcqFQew13MHlOE3p64ABiNFIV5gwxhM81Ly3hPrEpEQD"
        - name: TWITTER_AT
          value: "871446601000202244-VUIk9PEITo7RSIFhENov1L7dqOsBpjC"
        - name: TWITTER_ATS
          value: "a4vbDWF9URHpcO5IKeGBwzKgeBGD9K08bOUk55Yo0kSSG"
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: susi-tweetbot
      restartPolicy: Always
